#!/bin/bash

set -e

cd `dirname $0`

BUILD=$PWD


echo saxon

if [ ! -d /tmp/jars ]; then
mkdir /tmp/jars
fi

cd /tmp/jars

if [ ! -f saxon9he.jar ]; then
    wget http://central.maven.org/maven2/net/sf/saxon/Saxon-HE/9.8.0-3/Saxon-HE-9.8.0-3.jar
    mv Saxon-HE-9.8.0-3.jar saxon9he.jar
fi

ls /tmp/jars

