#!/bin/bash

set -e

if [ ! -f ./saxon9he.jar ]; then
    if [ -f /tmp/jars/saxon9he.jar ]; then
	cp /tmp/jars/saxon9he.jar .
    else
	echo install saxon9he.jar eg run install-tools
    fi
fi


java -jar saxon9he.jar -o:index.html  src/mathml-web.xml src/mathml-web.xsl


if [ "$TRAVIS" = "true" ]; then

git clean -f

fi
