#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "usage: $0 /path/to/web-platform-tests"
    exit
fi

MATHML_CORE_URL=https://mathml-refresh.github.io/mathml-core
WPT_DIR=$1
WPT_SUBDIRS="mathml css/css-fonts/math-script-level-and-math-style css/css-text/text-transform/math"
PYTHON_SCRIPT=wpt-tests-generator.py
WARNING="This file was automatically generated by extract.sh. Do not edit."

echo "
#!/usr/bin/python
# $WARNING

from __future__ import print_function
import re

tests = {}
def add_test(section, path):
    if not section in tests:
        tests[section] = []
    tests[section].append(path)

def format_tests():
    all_tests = set()
    for section in sorted(tests):
        test_list=[]
        for test in sorted(tests[section]):
            # Adjust the path to match respec's assumptions.
            result = re.match( r'mathml/(.*)', test)
            if result:
                test = result.group(1)
            else:
                test = \"../%s\" % test
            all_tests.add(test)
            test_list.append(test)
        tests[section] = ','.join(test_list)

    print('Generating test data... ', end='')
    output = open('data-tests.js', 'w')
    print('// $WARNING', file=output)
    print('var dataTests = {', file=output)
    print('  \"implementation-report\": \"%s\",' % ','.join(sorted(all_tests)), file=output)
    for section in sorted(tests):
        print('  \"%s\" : \"%s\",' % (section, tests[section]), file=output)
    print('};\n', file=output)
    output.close()
    print('done')

    for test in sorted(all_tests):
        print(test)
" > $PYTHON_SCRIPT

for subdir in $WPT_SUBDIRS; do
    echo -n "Extracting tests from $WPT_DIR/$subdir... "
    find $WPT_DIR/$subdir -type f -name '*.html' | xargs grep '<link' | grep 'rel="help"' | grep $MATHML_CORE_URL | sed "s|$WPT_DIR/\($subdir/[^:]\+\):.\+$MATHML_CORE_URL/#\([^\"]\+\)\".\+|add_test('\2','\1')|" >> $PYTHON_SCRIPT
    echo "done"
done

echo "format_tests()" >> $PYTHON_SCRIPT
python $PYTHON_SCRIPT
